---
- name: Ensure Java is installed.
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present
- name: Add required dependencies.
  become: yes
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  become: yes
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    update_cache: true
- name: Install Elasticsearch.
  become: yes
  package:
    name: elasticsearch
    state: present

- name: configure elasticsearch
  become: yes
  command: 'sed -i "s/#network.host: 192.168.0.1/network.host: {{elasticsearch_ip}}/g" elasticsearch.yml'
  args:
    chdir: /etc/elasticsearch
- name: configure elasticsearch
  become: yes
  command: 'sed -i "s/#http.port: 9200/http.port: 9200/g" elasticsearch.yml'
  args:
    chdir: /etc/elasticsearch
  
- name: configure elasticsearch
  become: yes
  command: 'sed -i "s/#discovery.seed_hosts: /discovery.seed_hosts: /g" elasticsearch.yml'
  args:
    chdir: /etc/elasticsearch
- name: configure elasticsearch
  become: yes
  command: 'sed -i "s/host1/127.0.0.1/g" elasticsearch.yml'
  args:
    chdir: /etc/elasticsearch   
    
- name: configure elasticsearch
  become: yes
  command: 'sed -i "s/host2/[::1]/g" elasticsearch.yml'
  args:
    chdir: /etc/elasticsearch   

- name: Start Elasticsearch.
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: true

